### ISSUE TITLE
It seems that the cause is Next.js is doing Server Side Rendering and React-WordCloud can only be rendered on the client side, a quick fix would be:

### ISSUE THREAD

**Issue by luke-hanwook** [luke-hanwook/github-issue-management-practice#17]
It seems that the cause is Next.js is doing Server Side Rendering and React-WordCloud can only be rendered on the client side, a quick fix would be:

```jsx
{ process.browser && <ReactWordCloud words={props.words} options={props.wordCloudOptions} /> }
```

If it's a viable solution, maybe you can make React-WordCloud server-side-renderable, and that would be great.

[more one client-only rendering in next.js](https://haodong.io/render-client-side-only-component-in-next-js)

_Originally posted by @yifeikong in https://github.com/chrisrzhou/react-wordcloud/issues/65#issuecomment-692517927_

**Comment by jahua** [comment]
Application error: a client-side exception has occurred (see the browser console for more information).
