### ISSUE TITLE
For those suffering from this problem who need a solution while waiting for the pull request to be accepted, the following worked for me:

### ISSUE THREAD

**Issue by luke-hanwook** [luke-hanwook/github-issue-management-practice#8]
For those suffering from this problem who need a solution while waiting for the pull request to be accepted, the following worked for me:

1. Ensure that you have installed [frontend-collective-react-dnd-scrollzone](https://github.com/frontend-collective/frontend-collective-react-dnd-scrollzone) (normally pulled in automatically as a dependency of react-sortable-tree), fixed at version 1.0.2
2. Install the excellent [patch-package](https://github.com/ds300/patch-package) following the instructions described on its page (adding it as an npm  post-install script).
3. Create a `patches` folder in the root of your project
4. In that folder, create a file called frontend-collective-react-dnd-scrollzone+1.0.2.patch, with the following content:

````
diff --git a/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js b/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
index f1f66d6..085b87d 100644
--- a/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
+++ b/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js
@@ -178,7 +178,7 @@ function createScrollingComponent(WrappedComponent) {
         var _this2 = this;
 
         // eslint-disable-next-line react/no-find-dom-node
-        this.container = (0, _reactDom.findDOMNode)(this.wrappedInstance.current);
+        this.container = this.wrappedInstance.current;
 
         if (this.container && typeof this.container.addEventListener === 'function') {
           this.container.addEventListener('dragover', this.handleEvent);
````

5. run `npm  install`.  If you've correctly followed the instructions for installing `patch-package` then the patch will be applied.

All should now be working.

_Originally posted by @timothyarmes in https://github.com/frontend-collective/react-sortable-tree/issues/821#issuecomment-766860082_

**Comment by marqpdx** [comment]
Yes, this works! Thank you. I needed to use `--force` for the npm install, as well, after i did all the above steps:
```
npm install react-sortable-tree --force
```

Thank you!
